### PR TITLE
Add Famicom and TurboGrafx CD icons

### PR DESCRIPTION
**Pull request by SuperFromND**
Couple more icons!  First one isn't particularly common to have on a setup (most people just merge NES and Famicom into one section anyways), but famicom *is* a separate folder so I thought to include it.  TurboGrafx CD icon's pretty much only there because of Rondo of Blood. :p

### CODE REVIEW

**Comment by lilbud** [comment]
Did you make that famicom logo 800px wide?

**Comment by lilbud** [comment]
Few Requests:
* Make the famicom logo 800px wide (Looks a little small)
* Maybe make a PC Englin

**Comment by SuperFromND** [comment]
Alright, I fixed the Famicom logo and added a PC-Engine CD-ROM2 icon.  Should all be good now!

**Comment by lilbud** [comment]
These are good. The famicom logo is a little too big but it'll probably work. 
Are you making these at 1080x1080px?

**Comment by lilbud** [comment]
For future reference. The logos have to be 800px wide (except in some very rare cases, simple logos like gamecube.)

**Pull request merged**
